title: geos website
description: about stuff i made
theme: just-the-docs
color_scheme: dark

url: https://just-the-docs.github.io

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
